# Site settings
name: Ejemplo de colecciones en Jekyll
title: Ejemplo de colecciones en Jekyll
description: "Probando colecciones en Jekyll."
baseurl: "https://sidval.github.io/ejemplo-colecciones-jekyll/"

collections:
        sections:
                output: false
        chapters:
                output: true

# Build settings
markdown: kramdown
permalinks: pretty
