# Site settings
name: Jekyll Nested Collections Example
title: Jekyll Nested Collections Example
description: "Probando colecciones en Jekyll."
baseurl: "https://sidval.github.io/ejemplo-colecciones-jekyll/"

collections:
        sections:
                output: false
        chapters:
                output: true

# Build settings
markdown: kramdown
permalinks: pretty
